---
name: GitLab
version: 16.10.1-ce.0
slug: gitlab
description: This addon runs GitLab CE on Home Assistant.
arch:
- aarch64
- amd64
- armhf
- i386
startup: application
boot: auto
ports:
  80/tcp: 8081
  22/tcp: 8022
ingress: true
ingress_port: 80
ingress_entry: "/"
backup_pre: /opt/gitlab/bin/gitlab-backup create
backup_post: rm /data/gitlab/*.gz
options: {}
schema: {}
hassio_api: true
backup: hot
map:
  - backup:rw
  - config:rw
  - media:rw
