---
name: GitLab
version: 16.10.0-ce.0-6
slug: gitlab
description: This addon runs GitLab CE on Home Assistant.
arch:
- aarch64
- amd64
- armhf
- i386
startup: application
boot: auto
ports:
  80/tcp: 8081
  22/tcp: 8022
ingress: true
ingress_port: 80
ingress_entry: "/"
backup_pre: cp -R /etc/gitlab/* /data/etc/
options: {}
schema: {}
hassio_api: true
backup: cold
map:
  - backup:rw
  - config:rw
