name: GitLab CE
version: 18.3.5          # pick the latest stable release that your host can run
slug: gitlab
description: Self‑hosted GitLab Community Edition – perfect for code‑review, CI, and more.
arch: aarch64,armv7,amd64,386,armhf,armv6
startup: services          # start automatically
boot: auto

# Ports – change to whatever you want the external interface to be
ports:
  18080/tcp: 80
  18443/tcp: 443

# The data that GitLab needs to persist.  
# These bind‑mounts use the Home‑Assistant data store (/addons_data/<slug>) and
# are automatically created when the add‑on is installed.
volumes:
  - /addons_data/gitlab/opt:/var/opt/gitlab
  - /addons_data/gitlab/log:/var/log/gitlab
  - /addons_data/gitlab/etc:/etc/gitlab

# Options you can edit in the HA UI – this lets you change the public URL.
options:
  external_url: "http://<YOUR_HOST_IP>:18080"

# Validation schema for the options block
schema:
  external_url: str

# Optional: Override the entrypoint to inject the external_url into the omnibus config
environment:
  GITLAB_OMNIBUS_CONFIG: "external_url '${options.external_url}';"

# You can leave the image field blank and use the Dockerfile below to pull the official image
# image: gitlab/gitlab-ce:latest